# Generated by Django 4.0.1 on 2022-01-22 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField(auto_now=True)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('point', models.DecimalField(decimal_places=3, max_digits=6)),
                ('points', models.JSONField()),
                ('coeficients', models.JSONField()),
                ('quoats', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('edu_program', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='speciality',
            constraint=models.UniqueConstraint(fields=('name', 'edu_program'), name='UNIQUE_name_edu'),
        ),
        migrations.AddField(
            model_name='entrants',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DB.faculty'),
        ),
        migrations.AddField(
            model_name='entrants',
            name='speciality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DB.speciality'),
        ),
        migrations.AddField(
            model_name='entrants',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DB.university'),
        ),
    ]
