# Generated by Django 4.0.1 on 2022-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['name'], name='DB_faculty_name_5d9391_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['name', 'edu_program'], name='DB_speciali_name_1988e8_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['name'], name='DB_universi_name_3832e3_idx'),
        ),
    ]
